version: '3.6'
networks:
  eds-network:
    driver: bridge

services:
  # Kakfa service
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - eds-network

  broker:
    image: confluentinc/cp-kafka:7.4.0
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - eds-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - eds-network

  #Promotion services
  promotion-service:
    container_name: promotion-service
    build:
      context: .
      dockerfile: app/promotion/deployment/Dockerfile
    restart: always
    volumes:
      - ./app/promotion:/app/app/promotion
    ports:
      - "8001:8001"
    networks:
      - eds-network

  #Catalog services
  #  catalog-service:
  #    container_name: catalog-service
  #    build:
  #      context: .
  #      dockerfile: app/catalog/deployment/Dockerfile
  #    # restart: always
  #    volumes:
  #      - ./app/catalog:/app/app/catalog
  #    ports:
  #      - "8081:8081"
  #    networks:
  #      - eds-network
  
